disabled_rules: # rule identifiers to exclude from running
  - line_length
  - nesting
  - identifier_name
  - large_tuple
  - file_length

statement_position:
  statement_mode: uncuddled_else

function_body_length:
  - 75 # warning

opt_in_rules:
  - vertical_whitespace
  - operator_usage_whitespace

trailing_comma:
  mandatory_comma: true

swiftlint_version:
  - 0.17.0
